version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: "tensorflow"
    - dependency-name: "tensorflow-text"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
