name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  # Change this to invalidate existing cache.
  CACHE_PREFIX: v1
  PYTHON_PATH: ./

jobs:
  checks:
    name: python ${{ matrix.python }} - ${{ matrix.task.name }}
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python: [3.8]
        task:
          - name: Style
            run: |
              isort --check .
              black --check .

          - name: Lint
            run: |
              flake8 .

          - name: Type check
            run: |
              mypy .

          - name: Test
            run: |
              pytest -v --color=yes tests/

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install prerequisites
        run: |
          pip install --upgrade pip setuptools wheel virtualenv

      - name: Set build variables
        shell: bash
        run: |
          # Get the exact Python version to use in the cache key.
          echo "PYTHON_VERSION=$(python --version)" >> $GITHUB_ENV
          echo "RUNNER_ARCH=$(uname -m)" >> $GITHUB_ENV
          # Use week number in cache key so we can refresh the cache weekly.
          echo "WEEK_NUMBER=$(date +%V)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        id: virtualenv-cache
        with:
          path: .venv
          key: ${{ env.CACHE_PREFIX }}-${{ env.WEEK_NUMBER }}-${{ runner.os }}-${{ env.RUNNER_ARCH }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('dev-requirements.txt') }}
          restore-keys: |
            ${{ env.CACHE_PREFIX }}-${{ env.WEEK_NUMBER }}-${{ runner.os }}-${{ env.RUNNER_ARCH }}-${{ env.PYTHON_VERSION }}-

      - name: Setup virtual environment (no cache hit)
        if: steps.virtualenv-cache.outputs.cache-hit != 'true'
        run: |
          test -d .venv || virtualenv -p $(which python) --copies --reset-app-data .venv
          . .venv/bin/activate
          pip install -e .[dev]
          git clone --branch=main https://github.com/google-research/t5x # TODO: pin to specific commit.
          cd t5x
          python3 -m pip install -e . -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
          # install promptsource, and fix the seqio dependency
          pip install promptsource
          pip uninstall -y t5
          pip install git+https://github.com/google-research/text-to-text-transfer-transformer.git
          # custom fixed seqio
          pip uninstall -y seqio seqio-nightly
          pip install git+https://github.com/hamishivi/seqio.git
          pip install tensorflow==2.9.0
          pip install tensorflow-text==2.9.0
          echo "----- ALL DEPENDENCIES INSTALLED -----"
          # next, we cache the tokenizers / HF splits used so we don't have to load them later.
          # This can take ~15 minutes.
          python3 -c "from transformers import AutoTokenizer; AutoTokenizer.from_pretrained('t5-base')"
          python3 -c "from transformers import AutoTokenizer; AutoTokenizer.from_pretrained('roberta-base')"
          python3 -c "from transformers import FlaxRobertaModel; FlaxRobertaModel.from_pretrained('hamishivi/fixed-roberta-base')"
          python3 -c "from transformers import FlaxRobertaModel; FlaxRobertaModel.from_pretrained('hamishivi/fixed-distilroberta-base')"

      - name: Setup virtual environment (cache hit)
        if: steps.virtualenv-cache.outputs.cache-hit == 'true'
        run: |
          . .venv/bin/activate
          pip install --no-deps -e .[dev]

      - name: Show environment info
        run: |
          . .venv/bin/activate
          which python
          python --version
          pip freeze

      - name: ${{ matrix.task.name }}
        run: |
          . .venv/bin/activate
          ${{ matrix.task.run }}

      - name: Clean up
        if: always()
        run: |
          . .venv/bin/activate
          pip uninstall -y hyper_task_descriptions
